"""Add date to Metrics

Revision ID: 3a28f587a810
Revises: 88eac68b0650
Create Date: 2024-12-22 14:01:41.061489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a28f587a810'
down_revision = '88eac68b0650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.drop_column('date_logged')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_logged', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
