"""Initial migration

Revision ID: 88eac68b0650
Revises: 
Create Date: 2024-12-22 11:24:18.517678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88eac68b0650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('SequelizeMeta')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_logged', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sleep_quality', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hydration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blood_glucose', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oxygen_saturation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol', sa.Float(), nullable=True))
        batch_op.alter_column('heart_rate',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('blood_pressure',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_column('date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('blood_pressure',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('heart_rate',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cholesterol')
        batch_op.drop_column('oxygen_saturation')
        batch_op.drop_column('blood_glucose')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('hydration')
        batch_op.drop_column('sleep_quality')
        batch_op.drop_column('date_logged')

    op.create_table('SequelizeMeta',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='SequelizeMeta_pkey')
    )
    op.create_table('Users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('isPremium', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Users_pkey'),
    sa.UniqueConstraint('email', name='Users_email_key'),
    sa.UniqueConstraint('email', name='Users_email_key1'),
    sa.UniqueConstraint('email', name='Users_email_key2')
    )
    # ### end Alembic commands ###
